name: Release Drafter

on:
  push:
    branches:
      - release
    pull_request:
      types:
        - opened
        - reopened
        - synchronize

jobs:
  update-release-draft:
    name: Update release draft.
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5.19.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}